image: java:8-jdk
stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build

build_publish:
  stage: build
  script:
    - rm -rf **/build/libs
    - chmod +x gradlew
    - ./gradlew build publish
  artifacts:
    paths:
      - 'build/libs/*.jar'
